### ISSUE TITLE
Add Python packages as a use case

### ISSUE THREAD

**Issue by rchincha** [cncf-tags/wg-artifacts#16]

**Comment by ktarplee** [comment]
Pip is the primary installation tool for Python packages and the primary package index is PyPI.org.  Binary packages are often in Wheel format (zip files with a .whl extension) and source packages (.tar.gz).   The python package index specification requires an endpoint to list all the available packages (e.g., on PyPI https://pypi.org/simple/) and one for each package (e.g, for numpy https://pypi.org/simple/numpy/) which includes all the versions for all the architectures and platforms.   Both endpoints use specially crafted HTML but a newer specification allows for the same information to be in JSON.  The HTML contains hyperlinks to the package archive files.  “pip install” only looks for packages by package name thus only uses the later interface but some tools and/or subcommands that search for packages might require the former.  PyPI currently has a major design problem in that to determine the package dependencies the package manager has to fully download the package.  The metadata is not available outside of the package archive.  As such, there is very minimal metadata available about packages directly available from the python package index interface.  It includes information like package name, version, architecture, platform, and python version all extracted from the filename of the archive.  They also have the concept of “yanked” packages.

The part of this interface that does map very well to OCI is that they store data.  In PyPI.org’s case they even reference packages (distribution files) by hash.  Storing each package (e.g., numpy) in its own repository and then using a single multi-arch image to represent each version of the package (e.g., reg.example.com/python/numpy:v1.4.5) works however with OCI one cannot reliably list repos under a given path (i.e., reg.example.com/v2/_catalog is not universally available and does not restrict by path) thus providing the package catalog is not possible when storing it in this format.  An alternative storage format is to put all the packages in a single repository and then use the tag as the package name.  Each multi-arch image then contains all the versions and all the arch/platforms for that project.  By listing all the OCI tags one can easily list all the packages.  This obviously feels like a hack.  **When storing python packages in the most straightforward way, OCI lacks the functionality to list all packages efficiently because it lacks the ability to list repositories or search across repositories.**

**Comment by rchincha** [comment]
@ktarplee thoughts about capturing some this more formally using: https://github.com/cncf-tags/wg-artifacts/blob/main/docs/pkgmgr/PKGMGR_TEMPLATE.md and submitting a PR?

**Comment by ktarplee** [comment]
I am working on this one.  You can assign it to me.
